language: generic

python:
  - 3.6

install: 
  - pip install --user sphinx sphinx_rtd_theme
  - sudo apt-get install mpich2 gfortran

script: bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "0a6446eb3ae3"
  - COMMIT_AUTHOR_EMAIL: "atmyers2@gmail.com"

addons:
  apt:
    packages:
      - doxygen
